services:
  - type: pserv
    name: tournest-mysql
    env: docker
    dockerfilePath: ./Dockerfile.mysql
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 3306

  - type: web
    name: tournest-backend-docker
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 8082
      - key: MYSQLHOST
        value: tournest-mysql
      - key: MYSQLPORT
        value: '3306'
      - key: MYSQLDATABASE
        value: homestayhub
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: tournest123
      - key: MAIL_USERNAME
        value: tournestofc@gmail.com
      - key: MAIL_PASSWORD
        value: rogkopleaitjqcgf
